-- Seed data for Curated Experience page sections

DELETE FROM page_sections WHERE page_slug = 'curated-experience';

INSERT INTO page_sections (page_name, page_slug, page_data, created_by, created_at, updated_at)
VALUES (
  'Curated Experience',
  'curated-experience',
  '{"hero":{"contents":[{"title":"CURATED EXPERIENCE","description":"Discover our carefully curated collection of premium travel experiences designed for those who value quality and precision","background":"https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1920&q=80"}]},"approachSection":{"title":"OUR APPROACH TO EXPERIENCE","description":"A selective collection of experiences designed for those who value quality and precision. From events to travel and wellness, each experience is curated to meet a consistent standard of excellence."},"highlightedExperience":{"title":"HIGHLIGHTED EXPERIENCE","items":[{"image":"https://images.unsplash.com/photo-1506784365066-81342ee5ff30?w=600&q=80","title":"MOVEMENT","description":"World-class physical practices that revive energy, strength, and natural body wellness","url":"/experiences/movement"},{"image":"https://images.unsplash.com/photo-1600298881974-6be191ceeda1?w=600&q=80","title":"SPA & BODY CARE","description":"Rejuvenating treatments and holistic therapies inspired by Indonesian wellness traditions","url":"/experiences/spa"},{"image":"https://images.unsplash.com/photo-1506157786151-b8491531f063?w=600&q=80","title":"FOREST & NATURE","description":"Immersive nature experiences designed to calm the mind and reconnect with the natural world","url":"/experiences/forest"}]},"whyCuratedExperience":{"title":"WHY CURATED EXPERIENCE?","items":[{"title":"MOVEMENT","description":"Mindful physical practices that restore energy, strength, and natural body rhythm."},{"title":"MOVEMENT","description":"Mindful physical practices that restore energy, strength, and natural body rhythm."},{"title":"MOVEMENT","description":"Mindful physical practices that restore energy, strength, and natural body rhythm."},{"title":"MOVEMENT","description":"Mindful physical practices that restore energy, strength, and natural body rhythm."},{"title":"MOVEMENT","description":"Mindful physical practices that restore energy, strength, and natural body rhythm."}]},"pickYourChoose":{"title":"PICK YOUR CHOOSE","selectedCategoryIds":[1,2,3,4,5],"buttonText":"START YOUR EXPERIENCE","buttonLink":"/contact-us","items":[]},"curatedExperiences":{"title":"CURATED EXPERIENCES","description":"Handpicked travel and wellness experiences across Indonesia''s most beautiful destinations","selectedCategoryIds":[1,2,3,4,5],"items":[]},"ctaSection":{"title":"Ready to Book Your Experience?","description":"Get in touch with our team to customize your perfect journey","buttonText":"Contact Us","buttonLink":"/contact-us"}}',
  1,
  NOW(),
  NOW()
);
