name = "takshaka-project"
compatibility_date = "2026-02-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "nextcms-base"
database_id = "cd780285-ccef-43bb-bacf-10ffd7b85c4e"
migrations_dir = "drizzle"
